services:
  fs:
    image: factorio-server
    container_name: the_factory
    tty: true
    stdin_open: true
    ports:
     - "34197:34197/udp"
    volumes:
     - ./ServerFiles/saves:/opt/factorio/saves
     - ./ServerFiles/mods:/opt/factorio/mods
    environment:
     - TZ=America/Chicago

volumes:
  save-data:
    external: true

