services:
  fs:
    image: captainlucian/factorio-server:latest
    container_name: the_factory
    tty: true
    stdin_open: true
    ports:
     - "34197:34197/udp"
    volumes:
     - ./ServerFiles/saves:/opt/factorio/saves
     - ./ServerFiles/mods/mod-list.json:/opt/factorio/mods/mod-list.json
     - ./ServerFiles/server-settings.json:/opt/factorio/data/server-settings.json
    environment:
     - TZ=America/Chicago
    cap_drop:
     - ALL
    cap_add:
     - CHOWN
     - dac_override
     - fowner
     - fsetid
     - kill
     - setgid
     - setuid
     - setpcap
     - net_bind_service
     - net_raw
     - sys_chroot
     - mknod
     - audit_write
     - setfcap
    security_opt:
     - no-new-privileges:false
    pids_limit: 30
volumes:
  save-data:
    external: true

