services:
  fs:
    image: captainlucian/factorio-server:latest
    container_name: the_factory
    tty: true
    stdin_open: true
    ports:
     - "34197:34197/udp"
    volumes:
     - ./ServerFiles/saves:/opt/factorio/saves
     - ./ServerFiles/mods:/opt/factorio/mods
     - ./ServerFiles/server-settings.json:/opt/factorio/data/server-settings.json
    environment:
     - TZ=America/Chicago

volumes:
  save-data:
    external: true

