services:
  fs:
    image: factorio-server
    container_name: the_factory
    tty: true
    stdin_open: true
    ports:
     - "34197:34197/udp"
    volumes:
     - save-data:/opt/factorio/saves
    environment:
     - TZ=America/Chicago

volumes:
  save-data:
    external: false

